apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: gl-reporting
  labels:
    app: gl-reporting-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gl-reporting-worker
  template:
    metadata:
      labels:
        app: gl-reporting-worker
    spec:
      serviceAccountName: gl-reporting-app-sa
      containers:
        - name: worker
          # Same image as backend — placeholder rewritten by the deploy
          # workflow to <ECR_REGISTRY>/gl-reporting-backend:<git-sha>.
          image: gl-reporting-backend:latest
          command: ["celery", "-A", "workers.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - secretRef:
                name: gl-reporting-secrets
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: QDRANT_URL
              value: http://qdrant.gl-reporting.svc.cluster.local:6333
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
